version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - mern-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge
